### ISSUE TITLE
`PolymakeExt` background task in precompilation

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1340] opened 2023-12-31 15:45 UTC
As seen e.g. in the Oscar CI (https://github.com/oscar-system/Oscar.jl/actions/runs/7364368265/job/20044672970#step:7:353) on julia 1.10.
```julia
PolymakeExt Waiting for background task / IO / timer.
[pid 3567] waiting for IO to finish:
 Handle type        uv_handle_t->data
 timer              0xa01af90->0x7f67395345b0
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.

[pid 3567] waiting for IO to finish:
 Handle type        uv_handle_t->data
 timer              0xa01af90->0x7f67395345b0
This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
```

**Comment by thofma** [comment] 2023-12-31 15:50
Hm, this was fixed with rc2, but now is back, see https://github.com/thofma/Hecke.jl/issues/1282. Weird

**Comment by thofma** [comment] 2023-12-31 16:27
Can you reproduce it locally?

**Comment by thofma** [comment] 2023-12-31 18:21
I open https://github.com/JuliaLang/julia/issues/52685.

**Comment by thofma** [comment] 2024-01-04 09:06
Closing this, since this is a problem in julia.

**Closed by thofma** 2024-01-04 09:06 UTC
